### ISSUE TITLE
DHCP server not working

### ISSUE THREAD

**Issue by NuAlex** [hassio-addons/addon-adguard-home#91]
# Problem/Motivation

I want to make AdGuard a DHCP server for all the clients in my network.
Doesn't seem to work at all.

## Expected behavior

Get a new IP from the defined range after executing:
```
ipconfig /release
ipconfig /Renew
```

## Actual behavior

Clients can't get a new IP address with a time out error:
`Unable to contact your DHCP server. Request has timed out.`

## Steps to reproduce
Configured settings:

![image](https://user-images.githubusercontent.com/38176824/103328228-d47da880-4a0c-11eb-800e-30756b53df42.png)

It saves the settings but clicking in "Enable DHCP server" doesn't do anything.

I'm on the same physical (switch) as my Home Assistant.

Please advise, I don't know how to troubleshoot this.

Thank you!

**Comment by NuAlex** [comment]
AdGuard [documentation ](https://github.com/AdguardTeam/AdGuardHome/wiki/DHCP#prerequisites) says "_Make sure that you run an OS on which AdGuard Home supports DHCP_" but it doesn't say which OS are supported... can you help?

**Comment by peitschie** [comment]
I'm having this same issue also with a Supervised install on Debian 10.

**Comment by Cyr-ius** [comment]
Same issue with Home Assistant OS 5.9 on Pi3B

**Comment by bangcrash** [comment]
Similar issue here, I have configured the DHCP settings but I can't enable the DHCP server, the button does not go solid when I hover over it and nothing happens when I click it

![image](https://user-images.githubusercontent.com/60600795/103525040-7a4e6e80-4e76-11eb-8b0e-6e1b11cc84db.png)

**Comment by Cyr-ius** [comment]
> Same issue with Home Assistant OS 5.9 on Pi3B
For information, I applied the same resolution => https://github.com/hassio-addons/addon-adguard-home/issues/89#issuecomment-752795170

**Comment by peitschie** [comment]
Can confirm this is still a problem 😺

**Comment by bangcrash** [comment]
After updating i still had the same problem but I've just been back to check and it send that it is resolved more for me

**Comment by Fabian2205** [comment]
Also can confirm that this is still a problem (Home Assistant OS 5.11, 64 Bit, RPi3B+)

**Comment by frenck** [comment]
Fixed in current dev, will be part of the upcoming 4.0.0 release.

**Comment by peitschie** [comment]
Thanks for addressing this @frenck !
